### PR TITLE
Use locally defined datetimeformatter to avoid exceptions during signing

### PR DESCRIPTION
**Pull request by gcuni**
While doing some performance work on a project that uses this library, I noticed that the signing process is resulting in exceptions thrown (2 per signing request). So a service processing 1000 rps to elastic search is internally generating 2000 exceptions per second. The reason for the exceptions is that the built-in java DateTimeFormatter.BASIC_ISO_DATE defines the date with the timezone as optional. You're always using a LocalDateTime which does not have a timezone so every time the jvm tries to pull the timezone it gets an exception. I've attached 2 flamegraphs, one before and one after so you can see the difference.

Here's what it looks like before the fix:
before-fix

And here's what it looks like after the fix:
after-fix

### CODE REVIEW

**Comment by lvh** [comment]
I don't have merge privileges, but this LGTM.

**Comment by thesmith** [comment]
I do apologise. I've totally missed this. That's very poor of me.

I'll merge and release.

**Comment by thesmith** [comment]
Done. v0.0.17

**Comment by lvh** [comment]
Awesome! @thesmith -- please don't apologize, I've had more SNAFUs with random open source projects I had laying around like this than I can count...

The reason I originally looked at this was because I was checking if I could update some of the dependencies. Assuming there's no breakage, would that be OK?

**Comment by thesmith** [comment]
Of course!

**Pull request merged**
